### ISSUE TITLE
How to get rid of poisoned orchestrations

### ISSUE THREAD

**Issue by yell0wfl4sh** [Azure/durabletask#842] opened 2022-12-12 18:13 UTC
We noticed around 100 orchs are continuously throwing the following log event: `Message [] with ID 073c014b-eb87-48e5-88b1-f67b21bf1886 has been dequeued 24489 times and is now considered poison`

What does this exactly imply and how can we get rid of these?

**Comment by cgillum** [comment] 2022-12-12 18:22
It means there's a message in the queue is failing to be processed repeatedly. There are several different potential causes for this. For example, if the message content (typically an orchestration input or activity output) is unable to be deserialized. I would try to correlate it with other logs related to your instance - I'd expect there to be another error explaining why the message fails to get processed.

The fact that the message is described as `[]` makes me think it's a low-level failure - we can't even parse the basic metadata. Unless you can find the root cause and mitigate that, it might be necessary to temporarily stop your app and then try to manually delete these messages to make these errors go away.

**Comment by lilyjma** [comment] 2023-01-31 22:09
@yell0wfl4sh - Looks like Chris addressed your question. I'm closing this issue for now. If you have more questions, please reopen. Thanks!

**Closed** 2023-01-31 22:09 UTC
