### ISSUE TITLE
Dequeue suspended from a queue causing hang for several orchestrations

### ISSUE THREAD

**Issue by yell0wfl4sh** [Azure/durabletask#816] opened 2022-11-01 09:12 UTC
We faced another scenario where orchestrations were hung for a day because dequeuing was suspended from a particular taskhub queue. We noticed that message count in queue was piling up with no decrement happening. 

Logs:
`The maximum orchestration message prefetch limit of 257 has been reached; fetching from taskhubsimulation-control-01 will be temporarily suspended until existing messages are consumed`

This is a major issue for us as it lead to direct customer impact. 
@cgillum: can you please elaborate more on this particular issue and what might have caused this. It is also becoming a challenge for us to create a reliable monitor to detect these kind of scenarios and take some mitigation step.

**Comment by cgillum** [comment] 2022-11-01 16:11
This log message means that something is blocking the consumption of messages in your control queue. This is not normal and could indicate some sort of hang in your orchestration code (or middleware code, if you use middleware). You will need to investigate to see where things are getting blocked - for example, do some orchestrations on this machine start running but fail to complete? Some of the [Durable Task Framework logs](https://github.com/Azure/durabletask/tree/main/src/DurableTask.Core/Logging#readme) may be able to help you pinpoint the problem.

**Comment by yell0wfl4sh** [comment] 2022-11-03 05:53
We also noticed this log : `TaskOrchestrationDispatcher-fbd42cf1adad4e4c94a45d6a9afee3a2-0: Delaying work item fetching because the current active work-item count (40) exceeds the configured maximum active work-item count (40)`

Going through durable task code, I think this is causing halt on dequeuing process from the queue. We saw that taskhub lease blob is not getting updated every 30 secs, and we saw cases where lease can be maintained by a single worker upto 3-4 days. Can you please add a bit more info on this, why a different node is taking lease even when the worker is at its maximum active work-item. Also, how is this value of 40 being calculated for a particular VM instance? `( 10 (ie. default max concurrency) * Cores )`?

**Comment by yell0wfl4sh** [comment] 2022-11-03 10:18
Also, In what scenarios do we `$"Skipping {this.leaseType} lease aquiring for {lease.PartitionId}");`

ref:
```
if (!this.shouldAquireLeaseDelegate(lease.PartitionId))
                {
                    this.settings.Logger.PartitionManagerInfo(
                        this.accountName,
                        this.taskHub,
                        this.workerName,
                        lease.PartitionId,
                        $"Skipping {this.leaseType} lease aquiring for {lease.PartitionId}");
                    continue;
                }

```

**Comment by jviau** [comment] 2022-11-08 18:10
Lease acquiring is not the root cause of this - this is just around controlling what worker is consuming orchestration messages from a given control queue. In Azure storage, orchestrations are round-robbined to control queues and activities all go to the work-item queue. Control queues are owned (leased) by a single worker, and all workers access the work-item queue. 

What @cgillum is talking about is that Azure Storage has [concurrency limits](https://github.com/Azure/durabletask/blob/main/src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs#L106) on it (they are configurable). This is to prevent out-of-memory issues and other pitfalls of trying to process too much at once. The problem you are encountering is that Azure Storage has dequeued its max concurrency and then _nothing_ is processing them. This typically indicates that you have a deadlock in your middleware, activity, or orchestration code - so durable-task is dequeuing and processing work items, but those work items get stuck and so durable task reaches max concurrency limit and stops processing any more work.

I would recommend getting a memory dump of your stuck worker and examining the threads and tasks in memory to see if you can identify what, if anything, is stuck (and where it is stuck).

**Comment by yell0wfl4sh** [comment] 2022-11-09 05:23
Thanks for informative reply @jviau, we are not able to repro it, we will get dump next time we see this issue!

**Comment by jviau** [comment] 2022-11-14 17:56
@yell0wfl4sh I am going to close this issue for now. If/when you have a memory dump and need additional assistance please re-open.

**Closed by jviau** 2022-11-14 17:56 UTC
