### ISSUE TITLE
The main orchestration takes a long time to enter the completed state even though all sub-orchestrations are complete

### ISSUE THREAD

**Issue by hsnsalhi** [Azure/durabletask#613] opened 2021-09-26 11:58 UTC
Hello,
I have a MainOrchestration which creates many SubOrchestrations in parallel and waits them to complete.
here is the test code

**MainOrchestration**
```csharp
public class MainOrchestration : TaskOrchestration<List<ExecutionDetails>, int>
{
  public override async Task<List<ExecutionDetails>> RunTask(OrchestrationContext context, int subOrchestrationCount)
  {
    var listInstances = new List<Task<ExecutionDetails>>();
    for (int i = 0; i < subOrchestrationCount; i++)
    {
      var instance = context.CreateSubOrchestrationInstance<ExecutionDetails>(typeof(SubOrchestration), $"suborchestration[{i}]");
      listInstances.Add(instance);
    }
    Console.WriteLine($"{context.CurrentUtcDateTime:yyyy-MM-dd HH:mm:ss.fff} - waiting for suborchestrations to complete");
    var results = await Task.WhenAll(listInstances);
    Console.WriteLine($"{context.CurrentUtcDateTime:yyyy-MM-dd HH:mm:ss.fff} - all suborchestrations complete, returning result");
    return new List<ExecutionDetails>(results);
  }
}
```

**SubOrchestration**
```csharp
public class SubOrchestration : TaskOrchestration<ExecutionDetails, string>
{
  public override async Task<ExecutionDetails> RunTask(OrchestrationContext context, string input)
  {
    var execDetails = new ExecutionDetails { StartTime = context.CurrentUtcDateTime };
    await context.ScheduleTask<string>(typeof(Activity1), input);
    execDetails.EndTime = context.CurrentUtcDateTime;
    return execDetails;
  }
}
```

**Activity1**
```csharp
	public class Activity1 : TaskActivity<string, string>
	{
		protected override string Execute(TaskContext context, string input)
		{
			string output = $"{DateTime.UtcNow:yyyy-MM-dd HH:mm:ss.fff} - {input}";
			Console.WriteLine(output);
			return output;
		}
	}
```

My problem is that when I set subOrchestrationCount to higher values (over 2000) MainOrchestration gets stuck in WhenAll even though all sub orchestrations are complete (checked their status in the database).

Used storage provider: [Microsoft SQL Provider](https://github.com/microsoft/durabletask-mssql)

I appreciate your help and suggestions.

**Comment by cgillum** [comment] 2021-09-27 17:39
Hi @hsnsalhi, I'm guessing this is likely an issue with the Microsoft SQL provider. Let me see if I can reproduce it and get back to you.

**Comment by hsnsalhi** [comment] 2021-09-27 20:13
Thank you Chriss, 
I am looking forward to your answer

**Comment by cgillum** [comment] 2021-09-27 22:16
I'm not sure if this is the source of your problem, but I did encounter a significant number of SQL deadlocks when trying to run a similar scenario. That will certainly cause big delays in processing since we may have to retry several times. I've opened a tracking issue for this here: https://github.com/microsoft/durabletask-mssql/issues/45

**Comment by cgillum** [comment] 2024-01-09 23:58
Closing since linked issue is closed.

**Closed by cgillum** 2024-01-09 23:58 UTC
