### ISSUE TITLE
Quotes added to string

### ISSUE THREAD

**Issue by nhuurnink** [Azure/durabletask#1022] opened 2023-12-29 10:47 UTC
After upgrading to 1.1.0, my durable functions break. The reason is:

```
string device = "test";
batchTasks.Add(context.CallActivityAsync(nameof(ProcessDeviceIdAct), deviceId));
```

When running:
```
public Task ProcessDeviceIdAct([ActivityTrigger] string deviceId)
{
 // deviceId contains quotes: \"test\", instead of simply "test"
}
```

**Comment by jviau** [comment] 2023-12-29 18:19
Duplicate of https://github.com/Azure/azure-functions-durable-extension/issues/2674

**Closed by jviau** 2023-12-29 18:19 UTC
